# Generated by Django 4.2.5 on 2023-11-28 20:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('admission_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universities.universitymodel')),
            ],
        ),
    ]
